config/routes.rb
PROJECT1::Application.routes.draw do

root :to => 'entries#new'

 get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'

resources :users
resources :entries do
    collection do
      get 'search'
    end
end
get '/entries/:id/:keyword', to: 'entries#keyword'
get '/new2', to: 'entries#new2'

post '/notify', to: 'entries#notify'

end

app/models/entry.rb
class Entry < ActiveRecord::Base
belongs_to(:user)

def alchemy
alchemy = "9ddce0957447a5027cf1a73b860383823614057f"
input = URI.escape(self.input)
results = HTTParty.get("http://access.alchemyapi.com/calls/text/TextGetRankedKeywords?outputMode=json&text=#{input}&apikey=#{alchemy}")
alchemyreturn = results["keywords"]
alchemyreturn.each do |keyword|
  keyword["text"]
end
return alchemyreturn
end

def self.wiki(arr)
  input = arr.gsub(" ","%20")
  results = HTTParty.get("http://en.wikipedia.org/w/api.php?format=json&action=query&list=search&srlimit=10&srsearch=#{input}")
  wikireturn = results["query"]["search"]
  return wikireturn
end


# def self.wiki_images(arr)
# input = arr.gsub(" ","%20")
#   results = HTTParty.get("http://en.wikipedia.org/w/api.php?format=json&action=query&prop=titles=#{input}")
#   wikireturn = results["query"]["search"]
#   return wikireturn
# end

def self.google(arr)
  google= "AIzaSyD1NWvixbIxmWtt2AMm7Ku64rOJUkdSCXk"
  input = CGI::escape(arr)
  response = HTTParty.get("https://www.googleapis.com/customsearch/v1?key=#{google}&cx=015698937417642655162:-drsz93czku&q=#{input}")
  results = response["items"]
  return results
end
def self.soundcloud(arr)
  soundcloud ="7ed26600f8fb7a4f4615218ac40d7a81"
  input = arr.gsub(" ","%20")
  results= HTTParty.get("http://api.soundcloud.com/tracks.json?client_id=#{soundcloud}&q=#{input}&limit=5&streamable=true&order=created_at")
  soundcloudreturn = results
  return soundcloudreturn
end


def self.youtube(arr)
  google= "AIzaSyD1NWvixbIxmWtt2AMm7Ku64rOJUkdSCXk"
  input = CGI::escape(arr)
  results= HTTParty.get("https://gdata.youtube.com/feeds/api/videos?q=#{input}&key=#{google}&max-results=1&alt=json")
  youtubereturn = results["feed"]["entry"][0]["id"]["$t"]
  return youtubereturn
end

# def self.echonest(arr)
#   echonest = "CNQ7EJLGCHNW8QOIT"
#   input = arr.gsub(" ", "%20")
#   results = HTTParty.get("http://developer.echonest.com/api/v4/song/search?api_key=#{echonest}&format=json&results=1&combined=#{input}")

# end

# def self.instagram(arr)
#   instagram = "fea8919ccf8a47daa6c5d77fb52e0fda"
#   input = arr.gsub(" ", "%20")
#   results = HTTParty.get("https://api.instagram.com/v1/tags/#{input}/media/recent?client_id=#{instagram}&format=json")
#    instagramreturn = JSON.parse("#{results}")
#  return instagramreturn

# end
# def nyt(arr)
# E674492D62783A2A0FBA9CCD14B75E19:6:69091683

# end


end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController

before_action :authenticate, only: [:edit, :index, :update, :destroy]

def index
  @entries= Entry.all
end

def notify
  if current_user.present?
  @email = current_user.email
  UserMailer.note_email(@email, @entry).deliver
  redirect_to :back
  else
  redirect_to login_path
  end
end

def show
  @entry = Entry.find(params[:id])
  @keywords = @entry.alchemy
  @array = @keywords.map { |kw| kw["text"] }

  #wiki
  # @wiki= Entry.wiki(@array[0])
  # @wiki_titles = @wiki.map { |title| title["title"] }
  # @wiki_snippet = @wiki.map { |snippet| snippet["snippet"] }
  #google
  @google= Entry.google(@array[0])
  @google_sorted = []
  @google.each do |result|
    begin
     @google_sorted << {
      title: result["title"],
      snippet: result["snippet"],
      image:  result["pagemap"]["cse_image"][0]["src"],
      link: result["link"]
     }
    rescue
    end
  end

  #souncloud
  @soundcloud = Entry.soundcloud(@array[0])

  #youtube
  @youtube = Entry.youtube(@array[0])
  #instagram
  # @instagram = Entry.instagram(@array[0])

  if params[:from_ajax]
    render 'show', layout: false
    return
  end

end

def keyword
  @entry = Entry.find(params[:id])
  @keywords = @entry.alchemy
  @array = @keywords.map { |kw| kw["text"] }
  @keyword = @array.index(params[:keyword])

  #wiki
  @wiki= Entry.wiki(@array[@keyword])
  @wiki_titles = @wiki.map { |title| title["title"] }
  @wiki_snippet = @wiki.map { |snippet| snippet["snippet"] }
  #google
  @google= Entry.google(@array[@keyword])
  @google_sorted = []
  @google.each do |result|
     @google_sorted << {
      title: result["title"],
      snippet: result["snippet"],
      image:  result["pagemap"]["cse_image"][0]["src"],
      link: result["link"]
    }
  end

  #souncloud
  @soundcloud = Entry.soundcloud(@array[@keyword])

  #youtube
  @youtube = Entry.youtube(@array[@keyword])
  #instagram
  # @instagram = Entry.instagram(@array[0])


end


def new
    @entry = Entry.new
end
def new2
    @entry = Entry.new
end

def create
    @entry = Entry.new(entry_params)
    if @entry.save
      respond_to do |format|
        format.html { redirect_to @entry }
        format.json { render json: @entry }
        format.js   { }
      end
    else
        redirect_to :new
    end
end

private
  def entry_params
    params.require(:entry).permit(:input, :number)
  end


end

app/views/entries/_entry.html.erb
<%= content_tag(:div, class: "entry", id: dom_id(entry), data: {entry_info: entry} ) do %>

<div class="categories">
  <ul>
    <li><a href="/entries/:id#general">General</a><li>
    <li><a href="/entries/:id#music">Music</a><li>
    <li><a href="/entries/:id#video">Video</a><li>
    <li><a href="/entries/:id#info">Info</a><li>
  </ul>
</div>

<h3> Entry </h3>
<p><%= @entry.input %></p>

<div class="notify">
  <p> Send yourself a notification email to follow up on this entry </p>
<%= form_tag(notify_path) do %>
<%= hidden_field_tag(:transcipt, @entry.input) %>
<%= submit_tag("Notify") %>
<% end %>
</div>


<h3> KeyWords </h3>

<div class="keywordbox">
<form action="/entries/<%= @entry.id %>/<%= params[:number] %>" method="get">
  <label for="number">#Number of Keywords</label>
  <select name="number">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5"selected>5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
  </select><br><br>
  <input type="submit" name="submit">
</form><br>

  <div class="keywords">
      <% @array.each do |keyword| %>
       <a id="keywords" href="/entries/<%= @entry.id %>/<%= keyword %>"><%= keyword %></a>
      <% end %>
  </div>
</div>
<br>
<div style="width:95%; height:2px; background:rgba(0,0,0,.05); margin: 0 auto"></div>

<br>

<h3 id="general"> General </h3>
<div style="width:95%; height:3px; background:rgba(0,0,0,.2); margin: 0 auto"></div>
<% @google_sorted.each do |result| %>

      <div class="search">
       <h4 class="searchtitle"><a href="<%= result[:link]%>"><%= result[:title] %></a><br></h4>
        <div class="searchsnippet"><p><%= result[:snippet] %></p></div>
      <div class="searchimage"><img class="thumbnail" src="<%= result[:image] %>"></div>
      </div>
<%end %>

<h3 id="music"> Music </h3>
      <div class="music">
        <iframe width="45%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= @soundcloud[0]["id"]%>&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe>
      </div>

  <h3 id="video"> Video </h3>
      <div class="video-container">
         <iframe src="http://www.youtube.com/embed/<%= @youtube[41..100]%>" frameborder="0" width="100%" hheight="400"></iframe>
      </div>


<!-- <h3> Instagram </h3>
<div class="instagram"
<iframe src="//instagram.com/p/mQF0LBowpt/embed/" width="45%" height="400" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
</div> -->

<h3 id="info"> Info </h3>
<% i = 0 %>
<% while i < 3 do %>
  <div class="wikisearch">
    <h4 class="wikititle"><%= @wiki_titles[0 + i] %></h4><br>
     <p class="wikisnippet"><%= strip_tags(@wiki_snippet[0 + i]) %></p><br>
  </div>
<% i += 1 %>
<%end %>



<% end %>

app/views/entries/create.js.erb
$.ajax({
    url: '/entries/<%= @entry.id %>',
    method: 'get',
    dataType: 'html',
    data: { from_ajax: true}
  }).done( function(htmlData) {
    $('body').append(htmlData);
});

app/views/entries/index.html.erb
<h3> Entries </h3>
<%= render "shared/entriestable" %>

app/views/entries/keyword.html.erb
<div class="categories">
  <ul>
    <li><a href="/entries/:id#general">General</a><li>
    <li><a href="/entries/:id#music">Music</a><li>
    <li><a href="/entries/:id#video">Video</a><li>
    <li><a href="/entries/:id#info">Info</a><li>
  </ul>
</div>

<h3> Entry </h3>
<p><%= @entry.input %></p>

<div class="notify">
  <p> Send yourself a notification email to follow up on this entry </p>
<%= form_tag(notify_path) do %>
<%= hidden_field_tag(:transcipt, @entry.input) %>
<%= submit_tag("Notify") %>
<% end %>
</div>


<h3> KeyWords </h3>

<div class="keywordbox">
<form action="/entries/<%= @entry.id %>/<%= params[:number] %>" method="get">
  <label for="number">#Number of Keywords</label>
  <select name="number">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5"selected>5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
  </select><br><br>
  <input type="submit" name="submit">
</form><br>

  <div class="keywords">
      <% @array.each do |keyword| %>
       <a id="keywords" href="/entries/<%= @entry.id %>/<%= keyword %>"><%= keyword %></a>
      <% end %>
  </div>
</div>
<br>
<div style="width:95%; height:2px; background:rgba(0,0,0,.05); margin: 0 auto"></div>

<br>

<h3 id="general"> General </h3>
<div style="width:95%; height:3px; background:rgba(0,0,0,.2); margin: 0 auto"></div>
<% @google_sorted.each do |result| %>

      <div class="search">
       <h4 class="searchtitle"><a href="<%= result[:link]%>"><%= result[:title] %></a><br></h4>
        <div class="searchsnippet"><p><%= result[:snippet] %></p></div>
      <div class="searchimage"><img class="thumbnail" src="<%= result[:image] %>"></div>
      </div>
<%end %>

<h3 id="music"> Music </h3>
      <div class="music">
        <iframe width="45%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= @soundcloud[0]["id"]%>&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe>
      </div>

  <h3 id="video"> Video </h3>
      <div class="video-container">
         <iframe src="http://www.youtube.com/embed/<%= @youtube[41..100]%>" frameborder="0" width="100%" hheight="400"></iframe>
      </div>


<!-- <h3> Instagram </h3>
<div class="instagram"
<iframe src="//instagram.com/p/mQF0LBowpt/embed/" width="45%" height="400" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
</div> -->

<h3 id="info"> Info </h3>
<% i = 0 %>
<% while i < 3 do %>
  <div class="wikisearch">
    <h4 class="wikititle"><%= @wiki_titles[0 + i] %></h4><br>
     <p class="wikisnippet"><%= strip_tags(@wiki_snippet[0 + i]) %></p><br>
  </div>
<% i += 1 %>
<%end %>

app/views/entries/new.html.erb
<body class="bg">
  <h3 style="position:fixed;font-family: 'Alegreya Sans'; margin-top: -55px; margin-left: 20%; z-index:1001;">You Can With Tucan</h3>
<div style="text-align: center; margin-top:30px;" >
  <%= button_to "Speech Input", { :action => "new2" }, :method => :get %>
</div>
<div id="welcome">
  <h3> Welcome to Tucan.</h3>
  <p> Tucan is better than a parrot sitting on your shoulder that just mimics everything you say. With Tucan, you can record conversations or input text and be provided a portal to relevant information about that conversation. No more taking down notes to remember to look something up. Tucan takes the notes, sets the reminders, and provides you with the best sources to start your further inquiry. </p>
</div>
<%= render "shared/textinputform" %>
</body>

app/views/entries/new2.html.erb
<body class="bg">
<h3 style="position:fixed;font-family: 'Alegreya Sans'; margin-top: -55px; margin-left: 20%; z-index:1001;">You Can With Tucan</h3>
<div style="text-align: center; margin-top:30px;">
  <%= button_to "Text Input", { :action => "new" }, :method => :get %>
</div>
<%= render "shared/speechinput" %>

<%= form_for Entry.new, remote: true do |f| %>

  <%= f.submit "Entry" %>
<% end %>
</body>

app/views/entries/search.html.erb
<!-- <h1>Search Results</h1>

<% @results.each do |result| %>
  <h3><%= result["trackName"] %></h3>
  <audio controls src="<%= result["previewUrl"] %>"></audio>
<% end %> -->

app/views/entries/show.html.erb
<div class="categories">
  <ul>
    <li><a href="/entries/:id#general">General</a><li>
    <li><a href="/entries/:id#music">Music</a><li>
    <li><a href="/entries/:id#video">Video</a><li>
    <li><a href="/entries/:id#info">Info</a><li>
  </ul>
</div>

<h3> Entry </h3>
<p><%= @entry.input %></p>

<div class="notify">
  <p> Send yourself a notification email to follow up on this entry </p>
<%= form_tag(notify_path) do %>
<%= hidden_field_tag(:transcipt, @entry.input) %>
<%= submit_tag("Notify") %>
<% end %>
</div>


<h3> KeyWords </h3>

<div class="keywordbox">
<form action="/entries/<%= @entry.id %>/<%= params[:number] %>" method="get">
  <label for="number">#Number of Keywords</label>
  <select name="number">
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5"selected>5</option>
    <option value="6">6</option>
    <option value="7">7</option>
    <option value="8">8</option>
    <option value="9">9</option>
    <option value="10">10</option>
  </select><br><br>
  <input type="submit" name="submit">
</form><br>

  <div class="keywords">
      <% @array.each do |keyword| %>
       <a id="keywords" href="/entries/<%= @entry.id %>/<%= keyword %>"><%= keyword %></a>
      <% end %>
  </div>
</div>
<br>
<div style="width:95%; height:2px; background:rgba(0,0,0,.05); margin: 0 auto"></div>

<br>

<h3 id="general"> General </h3>
<div style="width:95%; height:3px; background:rgba(0,0,0,.2); margin: 0 auto"></div>
<% @google_sorted.each do |result| %>

      <div class="search">
       <h4 class="searchtitle"><a href="<%= result[:link]%>"><%= result[:title] %></a><br></h4>
        <div class="searchsnippet"><p><%= result[:snippet] %></p></div>
      <div class="searchimage"><img class="thumbnail" src="<%= result[:image] %>"></div>
      </div>
<%end %>

<h3 id="music"> Music </h3>
      <div class="music">
        <iframe width="45%" height="400" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/<%= @soundcloud[0]["id"]%>&amp;auto_play=false&amp;hide_related=false&amp;visual=true"></iframe>
      </div>

  <h3 id="video"> Video </h3>
      <div class="video-container">
         <iframe src="http://www.youtube.com/embed/<%= @youtube[41..100]%>" frameborder="0" width="100%" hheight="400"></iframe>
      </div>


<!-- <h3> Instagram </h3>
<div class="instagram"
<iframe src="//instagram.com/p/mQF0LBowpt/embed/" width="45%" height="400" frameborder="0" scrolling="no" allowtransparency="true"></iframe>
</div> -->

<h3 id="info"> Info </h3>
<% i = 0 %>
<% while i < 3 do %>
  <div class="wikisearch">
    <h4 class="wikititle"><%= @wiki_titles[0 + i] %></h4><br>
     <p class="wikisnippet"><%= strip_tags(@wiki_snippet[0 + i]) %></p><br>
  </div>
<% i += 1 %>
<%end %>